"""Iterate the Ga melt temperature until DSMC delivers the target wafer-centre flux.

`sparta_ga.py --mode dsmc-hold --correct-from DIR` makes one correction: it scales the
previous run's saturation pressure by target / delivered centre flux. This driver repeats that
step per state until the delivered/target ratio is within --tolerance, or --max-iterations
corrections have been made. Only states that meet the tolerance may be described as
"flux-held"; the others are reported as not converged.

States come from cases/sparta_ga/ga_dsmchold.json (first correction, results/ga_dsmchold/NAME).
Further corrections are NAME_it2, NAME_it3, ... in the same results and record directories,
run through scripts/sparta_batch.py (memory-guarded). The tolerance, 1.5 %, is about three
times the statistical error of the centre flux (inner 10 mm, 6e5 particles).

Usage: python scripts/ga_flux_hold.py            # status table only
       python scripts/ga_flux_hold.py --iterate  # run further corrections until done
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIRST = ROOT / "cases/sparta_ga/ga_dsmchold.json"
NEXT = ROOT / "cases/sparta_ga/iterations/ga_dsmchold.json"  # same stem: same result directories
RESULTS = ROOT / "results/ga_dsmchold"


def ratio(run_dir):
    s = run_dir / "summary.json"
    if not s.exists():
        return None
    return json.loads(s.read_text(encoding="utf-8"))["outputs"]["centre_flux_over_target"]["dsmc"]


def chain(name):
    """Completed and pending iteration directories of one state, in order."""
    dirs = [RESULTS / name]
    k = 2
    while (RESULTS / f"{name}_it{k}").exists():
        dirs.append(RESULTS / f"{name}_it{k}")
        k += 1
    return dirs


def status(jobs, tol):
    rows = []
    for job in jobs:
        dirs = chain(job["name"])
        last = [d for d in dirs if ratio(d) is not None]
        r = ratio(last[-1]) if last else None
        rows.append({"job": job, "iterations": len(last), "last": last[-1] if last else None, "ratio": r,
                     "converged": r is not None and abs(r - 1.0) <= tol})
    return rows


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tolerance", type=float, default=0.015)
    ap.add_argument("--max-iterations", type=int, default=3)
    ap.add_argument("--iterate", action="store_true")
    args = ap.parse_args()
    jobs = json.loads(FIRST.read_text(encoding="utf-8"))["jobs"]
    while True:
        rows = status(jobs, args.tolerance)
        print(f"{'state':32s} iter  delivered/target  converged")
        for r in rows:
            print(f"{r['job']['name']:32s} {r['iterations']:4d}  "
                  f"{'-' if r['ratio'] is None else format(r['ratio'], '.3f'):>16s}  {r['converged']}")
        todo = [r for r in rows if r["last"] is not None and not r["converged"]
                and r["iterations"] < args.max_iterations]
        if not args.iterate or not todo:
            break
        nxt = []
        for r in todo:
            a = list(r["job"]["args"])
            a[a.index("--correct-from") + 1] = str(r["last"].relative_to(ROOT)).replace("\\", "/")
            nxt.append({"name": f"{r['job']['name']}_it{r['iterations'] + 1}", "args": a})
        NEXT.parent.mkdir(parents=True, exist_ok=True)
        NEXT.write_text(json.dumps({"description": "Generated by scripts/ga_flux_hold.py: next temperature "
                                    "correction for states outside tolerance.", "script": "scripts/sparta_ga.py",
                                    "jobs": nxt}, indent=2) + "\n", encoding="utf-8", newline="\n")
        rc = subprocess.run([sys.executable, str(ROOT / "scripts/sparta_batch.py"), str(NEXT),
                             "--retry-incomplete"]).returncode
        if rc != 0:
            print("batch reported failures; stopping", flush=True)
            sys.exit(1)
    unconverged = [r["job"]["name"] for r in status(jobs, args.tolerance) if not r["converged"]]
    if unconverged:
        print(f"not converged: {', '.join(unconverged)}")


if __name__ == "__main__":
    main()
