"""Provenance of the versioned study records: which committed code each one ran, and what changed since.

For every manifest in data/runs/studies/*.json, each recorded source hash (manifest
source_sha256, LF-normalized as manifest.py hashes) is compared with the current file. Where
they differ, the file's git history is searched for the commit whose version has the recorded
hash, and the commits that changed the file after it are listed. Hand-written impact notes
(IMPACT below) say whether a later change can alter the record's numbers; a mismatch without a
note is reported as "not reviewed". The result is written next to the records as
data/runs/studies/PROVENANCE.md, so that it is found with them rather than in commit messages.

The records themselves are never modified.

Usage: python scripts/record_provenance.py [--check]   (--check: exit 1 if a mismatch has no note)
"""

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STUDIES = ROOT / "data/runs/studies"

# (file, commit that changed it) -> why the change does not alter records made before it
IMPACT = {
    "src/mbe_twin/aperture.py": "Later changes only add optional arguments (`axis`, then `centre`) whose defaults reproduce the "
                                "earlier sources exactly (tests/test_aperture.py).",
    "scripts/nitrogen_aim_tolerance.py": "Input validation only: the script now reads the versioned scans and stops when a requested "
                                         "plate's record is missing; the tilt calculation is unchanged (commit 092d201).",
    "src/mbe_twin/heater.py": "Later change adds the optional platen; without it the model is the earlier one exactly "
                              "(regression test in tests/test_heater.py).",
    "scripts/heater_zones.py": "Later changes add the platen variations and optional heater limits to optimize(); without "
                               "limits the iteration is the earlier one (recorded heater_zones ranges reproduce bit for bit). The later "
                               "at_limit() is a new function; at_mean() and optimize() are unchanged.",
    "scripts/growth_window.py": "Later change adds the --held option (centre-flux-held Ga maps); the default path is unchanged.",
    "src/mbe_twin/beam.py": "Later change adds the cylinder and holder-lip occluders and an optional background-gas mean free "
                            "path; without one the flux is exactly the earlier one (tests/test_beam.py, zero-pressure regression).",
    "scripts/layout_comparison.py": "CHANGES RESULTS. After the 2026-10-01 project audit the Ga centre flux is held absolute "
                                    "(it followed each state's N before), every heater state is held to the element limit, and "
                                    "the N output is bounded by a coupled feed/pressure balance. The six-layout record "
                                    "layout_comparison.json (6aca3b3) is superseded for B and C by layout_comparison_bc.json; "
                                    "its A, C-Ga54, R0 and D window margins were computed with the old Ga protocol.",
    "data/design/design_envelope.json": "Later change adds the nitrogen_source and acceptance blocks and a note on the output "
                                        "bound; every input the earlier records read is unchanged.",
    "scripts/nitrogen_aim_study.py":"Later changes add command-line options (--aspects/--offsets/--angles) and record fields; "
                                     "the grid evaluation and seeds of the default run are unchanged.",
}


def sha_lf(data):
    return hashlib.sha256(data.replace(b"\r\n", b"\n")).hexdigest()


def git(*args):
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, check=True).stdout


def history(path):
    """(commit, subject, sha256 of the file at that commit), newest first."""
    out = []
    for line in git("log", "--format=%H%x09%s", "--", path).decode("utf-8", "replace").splitlines():
        h, subject = line.split("\t", 1)
        try:
            blob = git("show", f"{h}:{path}")
        except subprocess.CalledProcessError:
            continue
        out.append((h, subject, sha_lf(blob)))
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    lines = ["# Provenance of the study records",
             "",
             "Generated by `scripts/record_provenance.py`; do not edit by hand. Each record in this directory stores the "
             "SHA-256 of the source files that produced it. Where a file has changed since, the table names the commit "
             "whose version matches the recorded hash and the later commits that touched the file, with a note on whether "
             "the change can alter the record's numbers. The records are kept unchanged.",
             "",
             "| Record | File | Recorded version | Changed since by | Effect on the record |",
             "|---|---|---|---|---|"]
    unreviewed = []
    clean = []
    for rec in sorted(STUDIES.glob("*.json")):
        m = json.loads(rec.read_text(encoding="utf-8"))
        mismatches = []
        for path, recorded in m.get("source_sha256", {}).items():
            f = ROOT / path
            if f.exists() and sha_lf(f.read_bytes()) == recorded:
                continue
            hist = history(path)
            match = next((i for i, (_, _, s) in enumerate(hist) if s == recorded), None)
            if match is None:
                version, later = "no committed version (uncommitted working copy at run time)", hist[:1]
            else:
                version, later = f"`{hist[match][0][:7]}`", hist[:match]
            changed = "; ".join(f"`{h[:7]}` {s}" for h, s, _ in reversed(later)) or "-"
            note = IMPACT.get(path)
            if note is None:
                unreviewed.append(f"{rec.name}: {path}")
                note = "**not reviewed**"
            mismatches.append(f"| {rec.name} | `{path}` | {version} | {changed} | {note} |")
        if mismatches:
            lines.extend(mismatches)
        else:
            clean.append(rec.name)
    lines += ["", "Records whose every source file is unchanged since the run: " + (", ".join(clean) or "none") + "."]
    (STUDIES / "PROVENANCE.md").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print("\n".join(lines))
    if unreviewed:
        print("\nNot reviewed: " + ", ".join(unreviewed), file=sys.stderr)
        if args.check:
            sys.exit(1)


if __name__ == "__main__":
    main()
